import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Don Lee & Co is bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Don Lee & Co is bad</h1>
        
        <label className={styles.warningLabel}>This website will be taken down as soon as Don Lee pays teachers for thier work.</label>
        
        <p>The Korean based online English Language business run by founder Don Lee is a bad company to do business with.  Avoid working for or taking lessons with this academy.</p>
        
        <div className={styles.profileImg}>
          <img src="Don Lee profile.png" alt="Girl in a jacket"/>
        </div>

        <p>Link to Don Lee & Co's  
          <span> </span>
          <a href="https://www.donleecompany.com/home" rel="noreferrer">Website</a>
          <span> ,</span>
          <a href="https://www.linkedin.com/in/coachdonlee/" rel="noreferrer">LinkedIn</a>
          <span> ,</span>
          <a href="https://www.instagram.com/coachdonlee" rel="noreferrer">Instagram</a>
          <span> ,</span>
          <a href="https://www.facebook.com/donleeco" rel="noreferrer">Facebook</a>
          .
        </p>


        <h2>Story</h2>
        <p>My name is Richard (The creator of this site) and I taught as an independent instructor for Don Lee & Co between the end of October 2021 till mid February 2022.  Over these 5 months/payment periods I only received payment once and it wasn’t even a full month's salary.  Don kept promising over phone calls and emails to pay me my outstanding salary but has not done so to date.  </p>
        <p>I found out from my students, after joining Don Lee & Co, that their previous instructors had quit suddenly because they did not receive payment after lengthy negotiations with Don himself.   I contacted some of these instructors and they confirmed the stories.</p>

        <form action="submit" className={styles.complaintForm}>
          <h2>Siubmit a complaint</h2>
          <p>Have you had issues with Don Lee & Co?  Submit your complain here.</p>
          <input type="text" placeholder="Name" />
          <input type="email" placeholder="email"/>
          <input type="phone" placeholder="phone"/>
          <input type="text" placeholder="complaint"/>
          <button>Submit complaint</button>
        </form>

        <h2>Live preview of Don Lee & Co's website</h2>
        <div className={styles.livePreviewiFrame}>
          <iframe src="https://www.donleecompany.com/home"  title="Iframe Example"></iframe>
        </div>

      </main>
    </div>
  )
}
